### ISSUE TITLE
Version 2.5.0 fails to build on Heroku

### ISSUE THREAD

**Issue by dguettler** [froala/ember-froala-editor#31]
I'm getting the following error when trying to deploy application to Heroku using the standard build pack.

```
BroccoliMergeTrees: Expected Broccoli node, got undefined for inputNodes[0]
TypeError: BroccoliMergeTrees: Expected Broccoli node, got undefined for inputNodes[0]
    at BroccoliMergeTrees.Plugin (/tmp/build_65839bf19840f998ff0c9b06481c5c99/node_modules/broccoli-plugin/index.js:23:13)
    at new BroccoliMergeTrees (/tmp/build_65839bf19840f998ff0c9b06481c5c99/node_modules/ember-froala-editor/node_modules/broccoli-merge-trees/index.js:16:10)
    at Class.treeForVendor (/tmp/build_65839bf19840f998ff0c9b06481c5c99/node_modules/ember-froala-editor/index.js:49:12)
    at Class.superWrapper [as treeForVendor] (/tmp/build_65839bf19840f998ff0c9b06481c5c99/node_modules/core-object/lib/assign-properties.js:34:20)
    at Class._treeFor (/tmp/build_65839bf19840f998ff0c9b06481c5c99/node_modules/ember-cli/lib/models/addon.js:517:33)
    at Class.treeFor (/tmp/build_65839bf19840f998ff0c9b06481c5c99/node_modules/ember-cli/lib/models/addon.js:477:21)
    at project.addoError running: ember build --environment production 2>&1ns.map
.addon (/tmp/build_65839bf19840f998ff0c9b06481c5c99/node_modules/ember-cli/lib/broccoli/ember-app.js:525:20)
    at Array.map (native)
    at EmberApp.addonTreesFor (/tmp/build_65839bf19840f998ff0c9b06481c5c99/node_modules/ember-cli/lib/broccoli/ember-app.js:523:30)
    at EmberApp._processedVendorTree (/tmp/build_65839bf19840f998ff0c9b06481c5c99/node_modules/ember-cli/lib/broccoli/ember-app.js:960:29)
```

Version 2.4.2 which does not use `broccoli-merge-trees` deploys without issues.

Application environment
```
DEBUG: -------------------------------
DEBUG: Ember             : 2.12.0-beta.2
DEBUG: Ember Data        : 2.12.0-beta.4
DEBUG: jQuery            : 3.1.1
DEBUG: Ember Simple Auth : 1.2.0
DEBUG: -------------------------------
```

Let me know what other information I could provide to resolve this.

**Comment by Panman8201** [comment]
Interesting, that seems to be coming from [here](https://github.com/froala/ember-froala-editor/blob/v2.5.0/index.js#L49) but I'm unsure why. Perhaps it's due to the [super call](https://github.com/froala/ember-froala-editor/blob/v2.5.0/index.js#L44) but [ember-cli should properly handle that by default](https://github.com/ember-cli/ember-cli/blob/v2.12.0-beta.2/lib/models/addon.js#L698-L700). I assume you're also on ember-cli 2.12 beta??

**Comment by Panman8201** [comment]
Humm... seems as though `vendorTree` might not always exist. There are a couple examples of other addons working around this.

https://github.com/martndemus/ember-font-awesome/pull/121/files
https://github.com/dfreeman/ember-cli-node-assets/blob/master/lib/tree-for.js#L53-L59

**Comment by dguettler** [comment]
It's used within a full application (not in an addon).
I'm currently on `ember-cli: 2.12.0-beta.1`

**Comment by Panman8201** [comment]
I just published `2.5.1-beta.1`. Can you try that and let me know if it fixes the issue for you?

**Comment by Panman8201** [comment]
@dguettler any update on this? Just want to make sure things are working for you.

**Comment by dguettler** [comment]
Sorry for the delay, your update works!
Thank you.
